// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

var max = 4000000
var i =3
var sum=0
var s=''
var oldf = 1
var newf = 2
do{
    var h = fibu()
    oldf=newf
    newf=h
}
while (newf<=max)

function fibu(){        
    if ((oldf+newf) % 2 == 0 ) {
        sum=sum + (oldf+newf)
        s= s + '\x1b[32m' + (oldf+newf) + '+'
    }
    else {
        s= s + '\x1b[31m' + (oldf+newf) + '+'
    }

    return oldf+newf
}
console.log('Summe: ' + s + ' = ' + sum)